import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 手动配置侧边栏
  sidebar: [
    {
      label: '首页',
      type: 'doc', // 指向具体文档
      id: 'introduction', // 确保与 docs/introduction.md 文件的 id 匹配
    },

     // 侧边栏1
    {
      label: 'Git',
      type: 'category',
      link: { type: 'generated-index' }, // 自动生成的索引页面
      items: [
        {
          type: 'autogenerated',
          dirName: 'git', // Git 文档在 docs/git 目录下
        },
      ],
    },
    // 其他文档可以继续添加
  ],
};

export default sidebars;