import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

export default {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' 即当前 docs 文件夹
    },
  ],
};