name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Lint
        run: nr lint

      # GD
     # - name: SSH Deploy and Execute Build (Server 1)
        #uses: easingthemes/ssh-deploy@v4.1.10
        #env:
         # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 通过 GitHub Secrets 安全传递私钥
          #ARGS: '-avzr --delete'  # 传递给 rsync 的参数，确保删除远程不再需要的文件
          #SOURCE: 'build'  # 本地构建的文件夹
          #REMOTE_HOST: ${{ secrets.REMOTE_HOST }}  # 远程主机地址，通过 Secrets 配置
          #REMOTE_USER: 'root'  # 远程服务器用户名
          #TARGET: '/www/wwwroot/darklotus.cn/'  # 远程目标路径，将构建文件上传到该目录已经开启ssh密钥登陆

      # SH 
      #- name: SSH Deploy and Execute Build (Server 2)
       # uses: easingthemes/ssh-deploy@v4.1.10
        #env:
         # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}  # 通过 GitHub Secrets 安全传递私钥
          #ARGS: '-avzr --delete'  # 传递给 rsync 的参数，确保删除远程不再需要的文件
          #SOURCE: 'build'  # 本地构建的文件夹
          #REMOTE_HOST: ${{ secrets.REMOTE_HOST_2 }}  # 远程主机地址，通过 Secrets 配置
          #REMOTE_USER: 'root'  # 远程服务器用户名
          #TARGET: '/www/wwwroot/darklotus.cn/'  # 远程目标路径，将构建文件上传到该目录已经开启ssh密钥登陆


      #US
      - name: SSH Deploy and Execute Build (Server 2)
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_3 }}  # 通过 GitHub Secrets 安全传递私钥
          ARGS: '-avzr --delete'  # 传递给 rsync 的参数，确保删除远程不再需要的文件
          SOURCE: 'build'  # 本地构建的文件夹
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_3 }}  # 远程主机地址，通过 Secrets 配置
          REMOTE_USER: 'root'  # 远程服务器用户名
          TARGET: '/www/wwwroot/darklotus.cn/'  # 远程目标路径，将构建文件上传到该目录已经开启ssh密钥登陆

