name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: corepack enable

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install ni
        run: nci

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: nr build

      - name: Lint
        run: nr lint

      - name: SSH Deploy and Execute Build
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'
