name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Install correct version of docusaurus-plugin-vercel-analytics
        run: npm install docusaurus-plugin-vercel-analytics@3.5.2

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: SSH Deploy and Execute Build
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'
