name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest
        node: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Lint
        run: nr lint

      # 部署到服务器1 (端口22)
      - name: SSH Deploy to Server 1
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete --rsh="ssh -o StrictHostKeyChecking=no -p 22"'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'

      # 部署到服务器2 (端口22)
      - name: SSH Deploy to Server 2
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: '-avzr --delete --rsh="ssh -o StrictHostKeyChecking=no -p 22"'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'
