name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]  # 你可以根据需要添加 macos-latest, windows-latest
        node: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - name: Install dependencies
        run: |
          npm install  # 安装依赖，确保所有依赖都安装好

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Build
        run: npm run build  # 使用 npm run build 来执行构建，确保在 package.json 中定义了 build 脚本

      - name: Lint
        run: npm run lint  # 确保 lint 脚本已在 package.json 中定义

      - name: SSH Deploy and Execute Build
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'
