name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean npm cache
        run: npm cache clean --force  # 清理缓存

      - name: Install dependencies
        run: npm install  # 安装依赖

      - name: Build
        run: npm run build  # 执行构建

      - name: Lint
        run: npm run lint  # 执行 lint

      - name: SSH Deploy and Execute Build
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/darklotus.cn/index'
